"""initial schema

Revision ID: 54b99720166f
Revises:
Create Date: 2026-09-14 20:37:55.817770
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "54b99720166f"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

MYSQL_TABLE_OPTIONS = {"mysql_engine": "InnoDB", "mysql_charset": "utf8mb4"}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_logs",
        sa.Column(
            "audit_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("actor_platform", sa.String(length=32), nullable=True),
        sa.Column("actor_openid_masked", sa.String(length=128), nullable=True),
        sa.Column("target_type", sa.String(length=64), nullable=False),
        sa.Column("target_id_masked", sa.String(length=128), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("result", sa.String(length=32), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("audit_id"),
        **MYSQL_TABLE_OPTIONS,
    )
    op.create_index("ix_audit_created", "audit_logs", ["created_at"], unique=False)
    op.create_table(
        "event_types",
        sa.Column("event_key", sa.String(length=128), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("payload_schema", sa.JSON(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("subscribable", sa.Boolean(), nullable=False),
        sa.Column("deprecated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("event_key"),
        **MYSQL_TABLE_OPTIONS,
    )
    op.create_index(op.f("ix_event_types_enabled"), "event_types", ["enabled"], unique=False)
    op.create_table(
        "pairing_codes",
        sa.Column("code_hash", sa.String(length=64), nullable=False),
        sa.Column("platform", sa.String(length=32), nullable=False),
        sa.Column("openid", sa.String(length=128), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("approved_by", sa.String(length=128), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failed_attempts", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("code_hash"),
        **MYSQL_TABLE_OPTIONS,
    )
    op.create_index(
        "ix_pairing_expiry", "pairing_codes", ["expires_at", "consumed_at"], unique=False
    )
    op.create_table(
        "provider_instances",
        sa.Column("provider_instance_id", sa.String(length=64), nullable=False),
        sa.Column("provider_key", sa.String(length=128), nullable=False),
        sa.Column("capability", sa.String(length=24), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("interval_seconds", sa.Integer(), nullable=True),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("provider_instance_id"),
        **MYSQL_TABLE_OPTIONS,
    )
    op.create_index(
        "ix_provider_due", "provider_instances", ["enabled", "next_run_at"], unique=False
    )
    op.create_index(
        op.f("ix_provider_instances_provider_key"),
        "provider_instances",
        ["provider_key"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("platform", sa.String(length=32), nullable=False),
        sa.Column("openid", sa.String(length=128), nullable=False),
        sa.Column(
            "role", sa.Enum("user", "admin", name="user_role", native_enum=False), nullable=False
        ),
        sa.Column(
            "account_status",
            sa.Enum("active", "blocked", name="account_status", native_enum=False),
            nullable=False,
        ),
        sa.Column("display_name", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("platform", "openid"),
        **MYSQL_TABLE_OPTIONS,
    )
    op.create_index(op.f("ix_users_account_status"), "users", ["account_status"], unique=False)
    op.create_table(
        "webhook_receipts",
        sa.Column("receipt_id", sa.String(length=36), nullable=False),
        sa.Column("source_key", sa.String(length=128), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("receipt_id"),
        sa.UniqueConstraint("source_key", "external_id", name="uq_webhook_replay"),
        **MYSQL_TABLE_OPTIONS,
    )
    op.create_index(
        "ix_webhook_status", "webhook_receipts", ["status", "received_at"], unique=False
    )
    op.create_table(
        "event_aliases",
        sa.Column("alias_key", sa.String(length=128), nullable=False),
        sa.Column("event_key", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["event_key"], ["event_types.event_key"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("alias_key"),
        **MYSQL_TABLE_OPTIONS,
    )
    op.create_table(
        "event_occurrences",
        sa.Column("event_id", sa.String(length=36), nullable=False),
        sa.Column("event_key", sa.String(length=128), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("dedupe_key", sa.String(length=255), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("subject", sa.JSON(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["event_key"], ["event_types.event_key"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("event_id"),
        sa.UniqueConstraint("event_key", "dedupe_key", name="uq_event_dedupe"),
        **MYSQL_TABLE_OPTIONS,
    )
    op.create_index(
        "ix_event_occurred", "event_occurrences", ["event_key", "occurred_at"], unique=False
    )
    op.create_table(
        "observations",
        sa.Column(
            "observation_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("provider_instance_id", sa.String(length=64), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("identity", sa.String(length=255), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("state", sa.JSON(), nullable=False),
        sa.Column("source_metadata", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["provider_instance_id"],
            ["provider_instances.provider_instance_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("observation_id"),
        sa.UniqueConstraint("provider_instance_id", "identity", name="uq_observation_identity"),
        **MYSQL_TABLE_OPTIONS,
    )
    op.create_index(
        "ix_observation_observed",
        "observations",
        ["provider_instance_id", "observed_at"],
        unique=False,
    )
    op.create_table(
        "provider_checkpoints",
        sa.Column("provider_instance_id", sa.String(length=64), nullable=False),
        sa.Column("cursor", sa.JSON(), nullable=False),
        sa.Column("last_identity", sa.String(length=255), nullable=True),
        sa.Column("state_hash", sa.String(length=64), nullable=True),
        sa.Column("state", sa.JSON(), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.Column("lease_owner", sa.String(length=128), nullable=True),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["provider_instance_id"],
            ["provider_instances.provider_instance_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("provider_instance_id"),
        **MYSQL_TABLE_OPTIONS,
    )
    op.create_index("ix_provider_lease", "provider_checkpoints", ["lease_until"], unique=False)
    op.create_table(
        "subscriptions",
        sa.Column("platform", sa.String(length=32), nullable=False),
        sa.Column("openid", sa.String(length=128), nullable=False),
        sa.Column("event_key", sa.String(length=128), nullable=False),
        sa.Column("locale", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["event_key"], ["event_types.event_key"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["platform", "openid"], ["users.platform", "users.openid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("platform", "openid", "event_key"),
        **MYSQL_TABLE_OPTIONS,
    )
    op.create_index("ix_subscription_event", "subscriptions", ["event_key"], unique=False)
    op.create_table(
        "user_permissions",
        sa.Column("platform", sa.String(length=32), nullable=False),
        sa.Column("openid", sa.String(length=128), nullable=False),
        sa.Column("permission_key", sa.String(length=16), nullable=False),
        sa.Column("granted", sa.Boolean(), nullable=False),
        sa.Column("granted_by", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("permission_key IN ('chat', 'command')", name="ck_permission_key"),
        sa.ForeignKeyConstraint(
            ["platform", "openid"], ["users.platform", "users.openid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("platform", "openid", "permission_key"),
        **MYSQL_TABLE_OPTIONS,
    )
    op.create_table(
        "deliveries",
        sa.Column("delivery_id", sa.String(length=36), nullable=False),
        sa.Column("event_id", sa.String(length=36), nullable=False),
        sa.Column("event_key", sa.String(length=128), nullable=False),
        sa.Column("platform", sa.String(length=32), nullable=False),
        sa.Column("openid", sa.String(length=128), nullable=False),
        sa.Column("message", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "leased",
                "retry",
                "sent",
                "dead",
                name="delivery_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("lease_owner", sa.String(length=128), nullable=True),
        sa.Column("lease_token_hash", sa.String(length=64), nullable=True),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("platform_message_id", sa.String(length=128), nullable=True),
        sa.Column("last_error_code", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["event_id"], ["event_occurrences.event_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("delivery_id"),
        sa.UniqueConstraint("event_id", "platform", "openid", name="uq_delivery_target"),
        **MYSQL_TABLE_OPTIONS,
    )
    op.create_index(
        "ix_delivery_claim",
        "deliveries",
        ["platform", "status", "next_attempt_at", "lease_until"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("deliveries")
    op.drop_table("user_permissions")
    op.drop_table("subscriptions")
    op.drop_table("provider_checkpoints")
    op.drop_table("observations")
    op.drop_table("event_occurrences")
    op.drop_table("event_aliases")
    op.drop_table("webhook_receipts")
    op.drop_table("users")
    op.drop_table("provider_instances")
    op.drop_table("pairing_codes")
    op.drop_table("event_types")
    op.drop_table("audit_logs")
    # ### end Alembic commands ###
